// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	v1 "mesa-mestre/app/v1"
	"sync"
)

// Ensure, that DiningTableCreatorMock does implement v1.DiningTableCreator.
// If this is not the case, regenerate this file with moq.
var _ v1.DiningTableCreator = &DiningTableCreatorMock{}

// DiningTableCreatorMock is a mock implementation of v1.DiningTableCreator.
//
//	func TestSomethingThatUsesDiningTableCreator(t *testing.T) {
//
//		// make and configure a mocked v1.DiningTableCreator
//		mockedDiningTableCreator := &DiningTableCreatorMock{
//			CreateDiningTableFunc: func(ctx context.Context, number int32, seats int32) error {
//				panic("mock out the CreateDiningTable method")
//			},
//		}
//
//		// use mockedDiningTableCreator in code that requires v1.DiningTableCreator
//		// and then make assertions.
//
//	}
type DiningTableCreatorMock struct {
	// CreateDiningTableFunc mocks the CreateDiningTable method.
	CreateDiningTableFunc func(ctx context.Context, number int32, seats int32) error

	// calls tracks calls to the methods.
	calls struct {
		// CreateDiningTable holds details about calls to the CreateDiningTable method.
		CreateDiningTable []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Number is the number argument value.
			Number int32
			// Seats is the seats argument value.
			Seats int32
		}
	}
	lockCreateDiningTable sync.RWMutex
}

// CreateDiningTable calls CreateDiningTableFunc.
func (mock *DiningTableCreatorMock) CreateDiningTable(ctx context.Context, number int32, seats int32) error {
	if mock.CreateDiningTableFunc == nil {
		panic("DiningTableCreatorMock.CreateDiningTableFunc: method is nil but DiningTableCreator.CreateDiningTable was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Number int32
		Seats  int32
	}{
		Ctx:    ctx,
		Number: number,
		Seats:  seats,
	}
	mock.lockCreateDiningTable.Lock()
	mock.calls.CreateDiningTable = append(mock.calls.CreateDiningTable, callInfo)
	mock.lockCreateDiningTable.Unlock()
	return mock.CreateDiningTableFunc(ctx, number, seats)
}

// CreateDiningTableCalls gets all the calls that were made to CreateDiningTable.
// Check the length with:
//
//	len(mockedDiningTableCreator.CreateDiningTableCalls())
func (mock *DiningTableCreatorMock) CreateDiningTableCalls() []struct {
	Ctx    context.Context
	Number int32
	Seats  int32
} {
	var calls []struct {
		Ctx    context.Context
		Number int32
		Seats  int32
	}
	mock.lockCreateDiningTable.RLock()
	calls = mock.calls.CreateDiningTable
	mock.lockCreateDiningTable.RUnlock()
	return calls
}
