// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	v1 "mesa-mestre/app/v1"
	"sync"
)

// Ensure, that OnwerCreatorMock does implement v1.OnwerCreator.
// If this is not the case, regenerate this file with moq.
var _ v1.OnwerCreator = &OnwerCreatorMock{}

// OnwerCreatorMock is a mock implementation of v1.OnwerCreator.
//
//	func TestSomethingThatUsesOnwerCreator(t *testing.T) {
//
//		// make and configure a mocked v1.OnwerCreator
//		mockedOnwerCreator := &OnwerCreatorMock{
//			CreateOwnerFunc: func(ctx context.Context, name string, email string) error {
//				panic("mock out the CreateOwner method")
//			},
//		}
//
//		// use mockedOnwerCreator in code that requires v1.OnwerCreator
//		// and then make assertions.
//
//	}
type OnwerCreatorMock struct {
	// CreateOwnerFunc mocks the CreateOwner method.
	CreateOwnerFunc func(ctx context.Context, name string, email string) error

	// calls tracks calls to the methods.
	calls struct {
		// CreateOwner holds details about calls to the CreateOwner method.
		CreateOwner []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
			// Email is the email argument value.
			Email string
		}
	}
	lockCreateOwner sync.RWMutex
}

// CreateOwner calls CreateOwnerFunc.
func (mock *OnwerCreatorMock) CreateOwner(ctx context.Context, name string, email string) error {
	if mock.CreateOwnerFunc == nil {
		panic("OnwerCreatorMock.CreateOwnerFunc: method is nil but OnwerCreator.CreateOwner was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Name  string
		Email string
	}{
		Ctx:   ctx,
		Name:  name,
		Email: email,
	}
	mock.lockCreateOwner.Lock()
	mock.calls.CreateOwner = append(mock.calls.CreateOwner, callInfo)
	mock.lockCreateOwner.Unlock()
	return mock.CreateOwnerFunc(ctx, name, email)
}

// CreateOwnerCalls gets all the calls that were made to CreateOwner.
// Check the length with:
//
//	len(mockedOnwerCreator.CreateOwnerCalls())
func (mock *OnwerCreatorMock) CreateOwnerCalls() []struct {
	Ctx   context.Context
	Name  string
	Email string
} {
	var calls []struct {
		Ctx   context.Context
		Name  string
		Email string
	}
	mock.lockCreateOwner.RLock()
	calls = mock.calls.CreateOwner
	mock.lockCreateOwner.RUnlock()
	return calls
}
