// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"mesa-mestre/app/v1"
	"sync"
)

// Ensure, that PlateCreatorMock does implement v1.PlateCreator.
// If this is not the case, regenerate this file with moq.
var _ v1.PlateCreator = &PlateCreatorMock{}

// PlateCreatorMock is a mock implementation of v1.PlateCreator.
//
//	func TestSomethingThatUsesPlateCreator(t *testing.T) {
//
//		// make and configure a mocked v1.PlateCreator
//		mockedPlateCreator := &PlateCreatorMock{
//			CreatePlateFunc: func(ctx context.Context, name string, plateDescription string, price float64) error {
//				panic("mock out the CreatePlate method")
//			},
//		}
//
//		// use mockedPlateCreator in code that requires v1.PlateCreator
//		// and then make assertions.
//
//	}
type PlateCreatorMock struct {
	// CreatePlateFunc mocks the CreatePlate method.
	CreatePlateFunc func(ctx context.Context, name string, plateDescription string, price float64) error

	// calls tracks calls to the methods.
	calls struct {
		// CreatePlate holds details about calls to the CreatePlate method.
		CreatePlate []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
			// PlateDescription is the plateDescription argument value.
			PlateDescription string
			// Price is the price argument value.
			Price float64
		}
	}
	lockCreatePlate sync.RWMutex
}

// CreatePlate calls CreatePlateFunc.
func (mock *PlateCreatorMock) CreatePlate(ctx context.Context, name string, plateDescription string, price float64) error {
	if mock.CreatePlateFunc == nil {
		panic("PlateCreatorMock.CreatePlateFunc: method is nil but PlateCreator.CreatePlate was just called")
	}
	callInfo := struct {
		Ctx              context.Context
		Name             string
		PlateDescription string
		Price            float64
	}{
		Ctx:              ctx,
		Name:             name,
		PlateDescription: plateDescription,
		Price:            price,
	}
	mock.lockCreatePlate.Lock()
	mock.calls.CreatePlate = append(mock.calls.CreatePlate, callInfo)
	mock.lockCreatePlate.Unlock()
	return mock.CreatePlateFunc(ctx, name, plateDescription, price)
}

// CreatePlateCalls gets all the calls that were made to CreatePlate.
// Check the length with:
//
//	len(mockedPlateCreator.CreatePlateCalls())
func (mock *PlateCreatorMock) CreatePlateCalls() []struct {
	Ctx              context.Context
	Name             string
	PlateDescription string
	Price            float64
} {
	var calls []struct {
		Ctx              context.Context
		Name             string
		PlateDescription string
		Price            float64
	}
	mock.lockCreatePlate.RLock()
	calls = mock.calls.CreatePlate
	mock.lockCreatePlate.RUnlock()
	return calls
}
