// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package pggen

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.insertDiningTableStmt, err = db.PrepareContext(ctx, insertDiningTable); err != nil {
		return nil, fmt.Errorf("error preparing query InsertDiningTable: %w", err)
	}
	if q.insertOwnerStmt, err = db.PrepareContext(ctx, insertOwner); err != nil {
		return nil, fmt.Errorf("error preparing query InsertOwner: %w", err)
	}
	if q.insertPlateStmt, err = db.PrepareContext(ctx, insertPlate); err != nil {
		return nil, fmt.Errorf("error preparing query InsertPlate: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.insertDiningTableStmt != nil {
		if cerr := q.insertDiningTableStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertDiningTableStmt: %w", cerr)
		}
	}
	if q.insertOwnerStmt != nil {
		if cerr := q.insertOwnerStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertOwnerStmt: %w", cerr)
		}
	}
	if q.insertPlateStmt != nil {
		if cerr := q.insertPlateStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertPlateStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                    DBTX
	tx                    *sql.Tx
	insertDiningTableStmt *sql.Stmt
	insertOwnerStmt       *sql.Stmt
	insertPlateStmt       *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                    tx,
		tx:                    tx,
		insertDiningTableStmt: q.insertDiningTableStmt,
		insertOwnerStmt:       q.insertOwnerStmt,
		insertPlateStmt:       q.insertPlateStmt,
	}
}
