// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: fetch_owner_by_email.sql

package pggen

import (
	"context"
)

const fetchOwnerByEmail = `-- name: FetchOwnerByEmail :one
SELECT id, name, email, created_at
FROM owners
WHERE email = $1
`

func (q *Queries) FetchOwnerByEmail(ctx context.Context, email string) (Owner, error) {
	row := q.queryRow(ctx, q.fetchOwnerByEmailStmt, fetchOwnerByEmail, email)
	var i Owner
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}
