// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: insert_owner.sql

package pggen

import (
	"context"
	"database/sql"
)

const insertOwner = `-- name: InsertOwner :exec
INSERT INTO owners (name, email)
VALUES ($1, $2)
`

type InsertOwnerParams struct {
	Name  sql.NullString `json:"name"`
	Email sql.NullString `json:"email"`
}

func (q *Queries) InsertOwner(ctx context.Context, arg InsertOwnerParams) error {
	_, err := q.db.ExecContext(ctx, insertOwner, arg.Name, arg.Email)
	return err
}
