// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: insert_dining_table.sql

package pggen

import (
	"context"
)

const insertDiningTable = `-- name: InsertDiningTable :exec
INSERT INTO dining_tables (table_number, capacity, table_status)
VALUES ($1, $2, $3)
`

type InsertDiningTableParams struct {
	TableNumber int32  `json:"table_number"`
	Capacity    int32  `json:"capacity"`
	TableStatus string `json:"table_status"`
}

func (q *Queries) InsertDiningTable(ctx context.Context, arg InsertDiningTableParams) error {
	_, err := q.exec(ctx, q.insertDiningTableStmt, insertDiningTable, arg.TableNumber, arg.Capacity, arg.TableStatus)
	return err
}
