// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: insert_plate.sql

package pggen

import (
	"context"
)

const insertPlate = `-- name: InsertPlate :exec
INSERT INTO plates (plate_name, plate_description, price)
VALUES ($1, $2, $3)
`

type InsertPlateParams struct {
	PlateName        string  `json:"plate_name"`
	PlateDescription string  `json:"plate_description"`
	Price            float64 `json:"price"`
}

func (q *Queries) InsertPlate(ctx context.Context, arg InsertPlateParams) error {
	_, err := q.exec(ctx, q.insertPlateStmt, insertPlate, arg.PlateName, arg.PlateDescription, arg.Price)
	return err
}
