// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package pggen

import (
	"database/sql"
)

type Owner struct {
	ID        int32          `json:"id"`
	Name      sql.NullString `json:"name"`
	Email     sql.NullString `json:"email"`
	CreatedAt sql.NullTime   `json:"created_at"`
}
