// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package pggen

import (
	"context"
)

type Querier interface {
	FetchOwnerByEmail(ctx context.Context, email string) (Owner, error)
	InsertOwner(ctx context.Context, arg InsertOwnerParams) error
}

var _ Querier = (*Queries)(nil)
